# Generated by Django 2.2.8 on 2019-12-06 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Empleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fechaPublicacion', models.DateField(auto_now_add=True, null=True)),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(default='Otra', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Categoria_Empleo', to='empleos.Categoria')),
            ],
            options={
                'ordering': ('fechaPublicacion', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAplicacion', models.DateField(auto_now_add=True, null=True)),
                ('id_empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleo_a_postular', to='empleos.Empleo')),
                ('id_postulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Postulante_Empleo', to='empleos.Usuario')),
            ],
            options={
                'ordering': ('fechaAplicacion',),
            },
        ),
        migrations.AddField(
            model_name='empleo',
            name='id_ofertante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ofertante_Empleo', to='empleos.Usuario'),
        ),
    ]
