version: '2'

services:

  web:
    image: teamlinked2019/empleos:v2.4
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - /code:/var/lib/empleos
    ports:
      - "8001:8001"
    depends_on:
      - db
      - migration
    labels:
      io.rancher.scheduler.global: 'true'
  
  migration:
    image: teamlinked2019/empleos:v2.4
    command: python manage.py migrate --noinput
    volumes:
      - /code:/var/lib/empleos
    depends_on:
      - db
    restart: "no"
    labels:
      io.rancher.scheduler.global: 'true'
  
  db:
    image: postgres
    ports:
      - "5433:5432"
    labels:
      io.rancher.scheduler.global: 'true'
